package rf.foundation.numbering;

public enum NumberingType {
	QUOTATION_NUMBER,
	SHORT_QUOTATION_NUMBER,
	PROPOSAL_NUMBER,
	POLICY_NUMBER,
	SHORT_POLICY_NUMBER,
	ENDORSEMENT_NUMBER,
	CLAIM_NUMBER,
	NOTICE_NUMBER,
	BCP_TRANS_NUMBER,
	BCP_RECEIPT_NUMBER,
	BCP_PAYMENT_NUMBER,
	ORDER_NUMBER,
	SIMPLE_SEQUENCE,
	LONG_SEQUENCE,
	CARD_NUMBER,
	GL_SEQUENCE,
	CUSTOMER_CODE,
	CHANNEL_CODE;
}
