package rf.foundation.numbering;

public enum NumberingType {
	QUOTATION_NUMBER,
	PROPOSAL_NUMBER,
	POLICY_NUMBER,
	ENDORSEMENT_NUMBER,
	CLAIM_NUMBER,
	NOTICE_NUMBER,
	BILL_TRANS_NUMBER,
	ORDER_NUMBER,
	SIMPLE_SEQUENCE,
	LONG_SEQUENCE,
	CARD_NUMBER,
	CUSTOMER_CODE,
	CHANNEL_CODE;
}
