package rf.foundation.pub;

public enum BizCodeType {
	QUOTATION_NUMBER,
	POLICY_NUMBER,
	PROPOSAL_NUMBER,
	ENDORSEMENT_NUMBER,
	CARD_POLICY_NUMBER,
	CLAIM_NUMBER,
	BCP_COLLECTION_NUMBER,
	BCP_PAYMENT_NUMBER;
}
